### ISSUE TITLE
不能打包release版本，老哥，知道为什么吗

### ISSUE THREAD

**Issue by daixinghong** [Launcher3-dev/Launcher3#14]

**Comment by yuchuangu85** [comment]
@daixinghong 有没有提示什么错误，贴出来我看看

**Comment by daixinghong** [comment]
没有报错，现在有个新的问题，大哥有没有涉猎过，Android p 怎么在Androidstudio打包，并且保留quickstep模块




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Launcher3-dev/Launcher3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 晚上9:49
收件人:&nbsp;"Launcher3-dev/Launcher3"<Launcher3@noreply.github.com&gt;;
抄送:&nbsp;"带鱼"<1073620755@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Launcher3-dev/Launcher3] 不能打包release版本，老哥，知道为什么吗 (#14)





 
@daixinghong 有没有提示什么错误，贴出来我看看
