### ISSUE TITLE
prebuilts/framework_intermediates/libs/sysui_shared.jar not compatible with quickstep

### ISSUE THREAD

**Issue by sitatec** [Launcher3-dev/Launcher3#19]
Hi, 

First, thank you for making the effort of providing this repo, it's very helpful.

It looks like the sysui_shared.jar is not compatible with quickstep. [This folder (smartspace)](https://android.googlesource.com/platform/frameworks/base/+/master/packages/SystemUI/shared/src/com/android/systemui/shared/system/smartspace/) is missing from the provided jar.

When I compile without quickstep it works but if I try with quickstep it fail with this error:
> error: package com.android.systemui.shared.system.smartspace does not exist
import com.android.systemui.shared.system.smartspace.ISmartspaceTransitionController;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

Also, can you tell me what feature quickstep provide please?

---

你好，

首先，感谢您提供这个 repo 的努力，它非常有帮助。

看起来 sysui_shared.jar 与 quickstep 不兼容。 [这个文件夹 (smartspace)](https://android.googlesource.com/platform/frameworks/base/+/master/packages/SystemUI/shared/src/com/android/systemui/shared/system/smartspace/) 提供的 jar.

当我在没有 quickstep 的情况下进行编译时，它可以工作，但是如果我尝试使用 quickstep，它会失败并出现以下错误：
> error: package com.android.systemui.shared.system.smartspace does not exist
import com.android.systemui.shared.system.smartspace.ISmartspaceTransitionController;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

另外，你能告诉我快步提供了什么功能吗？

**Comment by yuchuangu85** [comment]
@sitatec 
I have not used quickstep , as far as I know, quickstep contains the function show recent application of the system, in addition, quickstep function is compiled under the system source code

**Comment by sitatec** [comment]
Ah ok thank you.
